name: Deploy

on:
  release:
    types: [ published ]

jobs:

  deploy:
    name: Build/Coverage/Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - name: Get npm cache path
        id: npm-cache-path
        run: echo "::set-output name=path::$(npm config get cache)"
      - name: Check for npm cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-path.outputs.path }}
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: Clean install node modules (if no cache)
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install node modules (cached)
        if: steps.npm-cache.outputs.cache-hit == 'true'
        run: npm i

      - name: Build project
        run: npx nx build keep-updated

      - name: Test & coverage
        run: npx nx test keep-updated --codeCoverage --coverageReporters=lcov

      - name: Report to Codacy
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: 'coverage/packages/*/lcov.info'
      - name: Report to Code Climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{ github.workspace }}/coverage/packages/*/lcov.info:lcov
#      - name: Report to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./coverage/cobertura-coverage.xml
#          flags: release,jasmine

      - name: Publish to NPM (dry-run)
        run: npx nx publish keep-updated --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to NPM
        run: npx nx publish keep-updated
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
